### ISSUE TITLE
Expected identifier error in Internet Explorer 11

### ISSUE THREAD

**Issue by agonhasani** [jsdevtom/distinct-until-changed-immutable#1]
The library does not work in Internet Explorer 11.

https://github.com/jsdevtom/distinct-until-changed-immutable/blob/08e85f552a67929cef3ad4f885c636bcbe92c84c/src/deep-equals.ts#L131

![Screen Shot 2019-09-12 at 5 44 52 PM](https://user-images.githubusercontent.com/3299038/64799503-246cfd80-d585-11e9-8e56-e1aeaf33330d.png)

**Comment by jsdevtom** [comment]
@agonhasani Thanks for this and the email you sent. I don't have time to work on this now. You are more than welcome to create a pull request. 

All the best,

**Comment by jsdevtom** [comment]
Closing because @vesapupovci's now merged pull request should fix this. Thanks again.
